include: "rules/common.smk"

rule all:
    input:
        os.path.join(OUTPUT_DIR, "report", "raw.multiqc.html"),
        os.path.join(OUTPUT_DIR, "imputation", "STITCH.vcf.gz"),
        os.path.join(OUTPUT_DIR, "calls", "BaseVarC.vcf.gz")

rule report:
    input:
        os.path.join(OUTPUT_DIR, "report", "raw.multiqc.html")

##### Modules #####

include: "rules/qc.smk"
include: "rules/alignment.smk"
include: "rules/calling.smk"
include: "rules/imputation.smk"
include: "rules/gwas.smk"