include: "rules/common.smk"

rule all:
    input:
        expand(os.path.join(OUTPUT_DIR, "alignments", "{sample_id}.sorted.rmdup.realign.BQSR.cvg.bed.gz"), sample_id=[s[3] for s in SAMPLES]),
        expand(os.path.join(OUTPUT_DIR, "alignments", "{sample_id}.sorted.rmdup.realign.BQSR.bamstats"), sample_id=[s[3] for s in SAMPLES]),
        expand(os.path.join(OUTPUT_DIR, "calls", "{chr_id}.vcf.gz.tbi"), chr_id=[f"chr{i}" for i in range(1, 23)] + ["chrX", "chrY"]),
        expand(os.path.join(OUTPUT_DIR, "calls", "{chr_id}.cvg.tsv.gz.tbi"), chr_id=[f"chr{i}" for i in range(1, 23)] + ["chrX", "chrY"])

##### Modules #####

include: "rules/alignment.smk"
include: "rules/calling.smk"