name: nipt
channels:
  - conda-forge
  - bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bcftools=1.21
  - bedtools=2.31.1
  - bwa=0.7.18
  - cmake=3.25.1
  - fastp=0.23.4
  - fastqc=0.12.1
  - gatk4=4.3.0.0
  - multiqc=1.19
  - python=3.11.0
  - r-base=4.4
  - r-optparse=1.7.5
  - r-stitch=1.7.3
  - r-tidyverse=2
  - samtools=1.21
  - seqkit=2.9.0
  - snakemake=8.28.0
  - snakemake-interface-common=1.17.4
  - snakemake-interface-executor-plugins=9.3.3
  - snakemake-interface-report-plugins=1.1.0
  - snakemake-interface-storage-plugins=3.3.0
  - snakemake-minimal=8.28.0
  - snakemake-executor-plugin-slurm
