fqlist: "data/fq.list"

threads: 8

ref: "data/reference/Homo_sapiens_assembly38.fasta"
ref_index_prefix: "data/reference/Homo_sapiens_assembly38.fasta"
gatk_bundle_dir: "data/reference"

output_dir: output
log_dir: log