sample_list: data/nipt.sample200.list
file_pattern: data/reads/{sample_id}.R1.clean.fastq.gz
name_pattern: "{sample_id}.R1.clean"

output_dir: output_dbsnp156
benchmark_dir: benchmarks_dbsnp156
log_dir: log

# Please verify the platform that generated the sequencing files, as different
# sequencing platforms require specific names in the 'platform' argument.
# See https://samtools.github.io/hts-specs/SAMv1.pdf for details.
platform: ILLUMINA

ref: data/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
ref_fai: data/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fai
dbSNP: "data/gatk/dbsnp_156.hg38.vcf.gz"
gatk_bundle_dir: data/gatk

# The entire genome is divided into uniformly sized segments. Subsequently, 
# genotype imputation is carried out on each segment individually.
#
# Chunk_size, represents the size of the segments into which we want to divide 
# the genome. Larger chunks will require more computing resources and time. It
# is advisable to test different chunk sizes before starting to determine the 
# optimal parameters.
chunk_size: 5000000

# Skip positions in these chromosomal regions because there are no SNPs in these
# regions according to the 1000G reference panel.
exclude_regions:
  - chr1:130000001-140000000
  - chr9:50000001-60000000
  - chr13:1-15000000
  - chr14:1-15000000
  - chr15:1-15000000
  - chr16:40000001-45000000
  - chr21:1-5000000
  - chr22:1-10000000

